### PR TITLE
Somalia, Arab Formable, Gurani

### PR DESCRIPTION
**Pull request by Mr-Parrot**

### CODE REVIEW

**Comment by MadJamez** [comment]
@Mr-Parrot Can you remove the [common/Paradox Interactive - Shortcut.lnk] file?

**Review by MadJamez — CHANGES_REQUESTED** [review]
Looks good. Only found 1 error caused by your changes. Can you take a look at it?

 Error: "Unexpected token: state_muskogean_standard_of_living_add, near line: 1349" in file: "common/modifiers/content_1_modifiers.txt" near line: 1349

**Comment by MadJamez** [comment]
@Mr-Parrot Can you provide an exact list of new releasable, formable etc in this change? 
This is for the change log, so we can give an exact list of new countries and formables.

**Comment by Mr-Parrot** [comment]
> @Mr-Parrot Can you remove the [common/Paradox Interactive - Shortcut.lnk] file?

Sure , I have no clue how that ended up there.



> Looks good. Only found 1 error caused by your changes. Can you take a look at it?
> 
> Error: "Unexpected token: state_muskogean_standard_of_living_add, near line: 1349" in file: "common/modifiers/content_1_modifiers.txt" near line: 1349

I tried to get rid of it, but I could find no file called common/modifiers/content_1_modifiers.txt. However, I now found it in the base game files and moved and changed it, there shouldn't be an error anymore.



> @Mr-Parrot Can you provide an exact list of new releasable, formable etc in this change? This is for the change log, so we can give an exact list of new countries and formables.

Sure, new nation: Gurani new releasable: Seminole new formable: Arabia, Mashriq, and Pan Arabia

**Review by MadJamez — APPROVED** [review]

**Pull request merged**
